### ISSUE TITLE
Add map file for 5010 277

### ISSUE THREAD

**Issue by jdavisp3** [azoner/pyx12#41]
I'm interesting in adding support for 5010 277 files -- what's involved in developing a new map file?

**Comment by azoner** [comment]
I don't have a machine source for the 277. Many of the 5010 maps are not
yet part of core, but are in one of the branches.

The simplest process would be to just make a copy of the 4010, sit down
with the 4010 and 5010 versions and update the XML.  That spec is small
enough that it shouldn't take too much time.

---------------------
John Holland
john@zoner.org

**Comment by jdavisp3** [comment]
Sounds good, I will do that and submit a PR, thank you!
