### ISSUE TITLE
Trying to Contact John

### ISSUE THREAD

**Issue by aviars** [azoner/pyx12#46]
Hi John:  I am a Python developer working in health IT supporting the federal government.  I am writing an article about X12 and would really like to chat with you by phone for a few minutes.  Would you be up for a short call?

- Alan

aviars at videntity dot com

p.s. I couldn't find your email or a LinkedIn profile. So that is  why I contacted you via an issue request.

**Comment by azoner** [comment]
Glad to talk.

https://www.linkedin.com/in/john-holland-a5aa6613

---------------------
John Holland
azoner@gmail.com
