### ISSUE TITLE
Help - Parse EDI file into XML

### ISSUE THREAD

**Issue by lasarvit** [azoner/pyx12#55]
I  have seen this library but not able to locate any example to parse EDI file into XML. Can anyone of you please help.

**Comment by menacher** [comment]
See https://stackoverflow.com/a/52396604/596720

**Comment by azoner** [comment]
the command line utility included in the project "x12xml" does this - converts X12 contents into a pretty ugly and non-useful XML format.

I have more luck writing code to enumerate through the x12, pick out the elements that are useful, and create a JSON or XML version, using names that make much more sense in your specific use case.
