### ISSUE TITLE
XML map for 837D claim

### ISSUE THREAD

**Issue by etanzapinsky** [azoner/pyx12#57]
I'm working on a project where I'd like to parse the X12 837D claim format. I see the `pyx12/map/` directory which holds the various specs. Where can I find (or how can I generate) an xml file which'll be able to parse the dental version of the 837 spec to add to that directory?

**Comment by azoner** [comment]
I originally created those map files by hand.  Make a copy of one of the other 837 files and edit it.  It would take a few hours to work through the 837D implementation guide.

**Comment by etanzapinsky** [comment]
Sweet. Thanks for your work on this project!
