### ISSUE TITLE
pyx12 usage issue

### ISSUE THREAD

**Issue by pantegra** [azoner/pyx12#58]
I am trying to use the pyx12 module in parsing some 837I/P files.  I can import the module but none of the functions are there and can not be used.  Here is the error:
>>> import pyx12
>>> pyx12.x12context
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pyx12' has no attribute 'x12context'
I am not sure what is going on.  I used pip to install pyx12 so everything was installed correctly.

**Comment by azoner** [comment]
You need to separately import sub-modules.

Try
```
import pyx12
import pyx12.x12context

src = pyx12.x12context.X12ContextReader(param, errh, fd_in)

```
