### ISSUE TITLE
Help - Parse data in multiple files (not really an issue, a question)

### ISSUE THREAD

**Issue by arjuniyer1978** [azoner/pyx12#63]
Hello, Pardon my lack of python knowledge. 
We are looking to use this to generate ANSI 834 files.
Our files primarily have Loops 2000 and 2300 (apart from other loops, required header and trailer records).
We have data that will go in each of the loops in separate files.

Where do i start to generate a ANSi834 file where data is stored in multiple files.

Thank You.
Arjun

**Comment by azoner** [comment]
pyx12 is focused on reading/parsing X12, not so much on writing.  The X12Writer and Segment classes wrap basic element/segment/loop separators, and segment counting. These classes do not have any awareness of specific X12 transactions (like the 837).
