### ISSUE TITLE
835 - missing Adjustment Reason Code 

### ISSUE THREAD

**Issue by cwiese** [azoner/pyx12#64]
Ele 7 - (272) is not a valid code for Adjustment Reason Code  (CAS02)

Is there a way to add current codes -- OR -- just warn during validation

You do not happen to have an example of the looping over 835's?  I guess I could read the XML and come up with the structure.  Thanks

**Comment by azoner** [comment]
I will review the current adjustment reason codes.  This codeset is listed in the file codes.xml.

You can ignore external codesets with the command line flag --exclude_external_codes.  

For example:

x12valid.py ---exclude_external_codes adjustment_reason <file>

I haven't worked with 835 recently.  What loop in the 835 are you wanting to enumerate?  I would do something like:

    src = pyx12.x12context.X12ContextReader(param, errh, fd_in)
    for datatree in src.iter_segments('2300'): # enumerate 2300 
        # do something with a 2300 claim loop
        # we have access to the 2300 loop and all its children
        for loop2400 in datatree.select('2400'):
            print(loop2400.get_value('SV101'))

This is an 837 example.  Pick the 835 loop you're wanting to extract data from.

**Comment by cwiese** [comment]
yup - I get it now.   Thanks for checking on the CARC.  Where do you get the update XML from?  

Thanks.

**Comment by azoner** [comment]
The official codeset is published by x12.org

[http://www.x12.org/codes/claim-adjustment-reason-codes/](http://www.x12.org/codes/claim-adjustment-reason-codes/)

I have been removing some of the less-stable external codesets from pyx12.  We really want to validate what's baked into the 5010 implementation guide and will not change without a published addendum.

**Comment by azoner** [comment]
I'm going to remove this codeset from the specs.  There is a constant level of adds and deletions of codes.  Any list I build will never be or stay correct,

**Comment by azoner** [comment]
Removed the codeset.
